# Colors (Lain)

# Default colors
[colors.primary]
background = "#17282d"
foreground = '#C6C6C4'

# Normal colors
[colors.normal]
red     = '#cc814a'
green   = '#009F6D'
yellow  = '#f9ab00'
blue    = '#e3be87'
magenta = '#d68a71'
cyan    = '#8ac7c1'
white   = '#fffdd8'

